name: API Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - 'common-lib/**'
      - '.github/workflows/api.docker-image.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-24.04"
            arch: "amd64"
            image_repo: "ibabiankou/home-lab"
            python-version: "3.13"
          - os: "ubuntu-24.04-arm"
            arch: "arm64"
            image_repo: "ibabiankou/home-lab"
            python-version: "3.13"
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Calculate image tag
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          imageTag="narrator-api-${calculatedSha}"
          echo "IMAGE_TAG=${{ matrix.arch }}-${imageTag}" >> $GITHUB_ENV
          
          # Save the common part of the tag as step output
          echo "image_tag=${imageTag}" >> $GITHUB_OUTPUT

      - name: Confirm which image is being pushed
        run: echo "${{ matrix.image_repo }}:${{ env.IMAGE_TAG }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: api/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ matrix.image_repo }}:${{ env.IMAGE_TAG }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        image_repo: ["ibabiankou/home-lab"]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        run: |
          AMD_TAG="${{ matrix.image_repo }}:amd64-${{ needs.build.outputs.image_tag }}"
          ARM_TAG="${{ matrix.image_repo }}:arm64-${{ needs.build.outputs.image_tag }}"
          MULTIARCH_TAG="${{ matrix.image_repo }}:${{ needs.build.outputs.image_tag }}"
          
          docker buildx imagetools create -t $MULTIARCH_TAG $AMD_TAG $ARM_TAG

      - name: Invoke workflow in home-lab-gitops
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_tag.yml
          repo: ibabiankou/home-lab-gitops
          inputs: '{ "image_repo": "${{ matrix.image_repo }}", "image_tag": "${{ needs.build.outputs.image_tag }}" }'
          token: "${{ secrets.GH_PAT_RW }}"
