name: Speech Generator Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'speech-generator/**'
      - 'common-lib/**'
      - '.github/workflows/speech.docker-image.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Calculate image tag
        id: vars
        run: |
          echo "IMAGE_REPOSITORY=ibabiankou/home-lab" >> $GITHUB_ENV
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "IMAGE_TAG=narrator-speech-$calculatedSha" >> $GITHUB_ENV

      - name: Confirm which image is being pushed
        run: echo "${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: speech-generator/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Invoke workflow in home-lab-gitops
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_tag.yml
          repo: ibabiankou/home-lab-gitops
          inputs: '{ "image_repo": "${{ env.IMAGE_REPOSITORY }}", "image_tag": "${{ env.IMAGE_TAG }}" }'
          token: "${{ secrets.GH_PAT_RW }}"
